version: '3'
services:
  api:
    container_name: hex-api
    image: "hex-example"
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    volumes:
      - ./python:/code/python
    expose:
      - "8000"
    ports:
      - 0.0.0.0:8000:8000